version: '3'
services:
  # MySQL Database
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - back
  # Spring Boot Backend
  spring-backend:
    image: moez063719/achat_backend:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.hibernate.ddl-auto: update
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldb
    networks:
      - back
  # Angular Frontend
  angular-frontend:
    image: moez063719/achat_frontend:latest
    ports:
      - "8099:80"
    depends_on:
      - spring-backend
    networks:
      - back

volumes:
  dockerAngularSpringDatabaseData:

networks:
  back:
  front:
