version: '3'
services:
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    networks:
      - my-network

  spring-boot-app:
    image: azizbenzarti/devopsapp
    ports:
      - "8088:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/achatdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - .m2:/var/lib/jenkins/.m2
    networks:
      - my-network
  angular-app:
    image: azizbenzarti/achat_frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
    networks:
      - my-network

networks:
  my-network:
