version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
  spring-app:
    image: azizbenzarti/devopsapp:latest
    container_name: spring-boot
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/achatdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8082:8082"
 angular-app:
    image: azizbenzarti/achat_frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app
    networks:
      - my-network
networks:
  my-network:
  